services:
  postgresdb:
    image: 'postgres:16.3-alpine3.20'
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - 'POSTGRES_DB=belajar-postgresql-dasar'
      - 'POSTGRES_USER=zvZnK2CJAo0Xw'
      - 'POSTGRES_PASSWORD=nljMTxE2XU1Zp'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - '$PWD/belajar-postgresql-dasar-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    expose:
      - '5432'